# .github/FUNDING.yml
paypal: denixbug
# You can also add other platforms like:
# github: [your-username]  # if you set up GitHub Sponsors
# ko_fi: your-kofi-username
# custom: ["https://paypal.me/denixbug"]
